triggers:
- description: null
  envs: []
  last_enabled_at: 2024-08-04 04:21:24.175194+00:00
  name: Real time Wind Turbine Power prediction
  pipeline_uuid: predict
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-08-04 04:19:00+00:00
  status: active
  token: 47c855cead7d4dd28a79b4ca328f609d
  variables: {}
